[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "docxcompose_tes"
description = "Python library for concatenating/appending Microsoft Word (.docx) files."
readme = "README.rst"
license = {text = "MIT"}
requires-python = ">=3.13"
dependencies = [
    'lxml',
    'python-docx >= 1.2.0',
    'six',
    'babel',
]


# Only version is dynamic
dynamic = ["version"]

# All other fields remain static
keywords = ["Python", "DOCX", "Word", "OOXML"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License"
]

[project.scripts]
docxcompose = "docxcompose.command:main"

[project.optional-dependencies]
test = ["pytest"]
tests = ["pytest"]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"

# declare readme dynamically via setuptools
[tool.setuptools.dynamic]
readme = { file = ["README.rst", "HISTORY.txt"], content-type = "text/x-rst" }
